name: "try-module.cloud"
description: "Publishes packages to try-module.cloud"
branding:
    icon: "package"
    color: "black"

inputs:
    organization:
        description: "Organization name"
        required: true
    directory:
        description: "Path to your module"
        required: true
    secret:
        description: "Secret key"
        required: true
    github-token:
        description: "GitHub token"
        required: true
outputs:
    url_commit:
        description: "URL of the published module for commit"
    url_branch:
        description: "URL of the published module for branch"
    url_pr:
        description: "URL of the published module for PR"
    command:
        description: "Command to install the published module"
runs:
    using: "node20"
    main: "dist/index.js"
